import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ApiTestingContractService {

  HTTP_GET_METHOD_NAME = 'GET';
  HTTP_POST_METHOD_NAME = 'POST';
  HTTP_PUT_METHOD_NAME = 'PUT';
  HTTP_DELETE_METHOD_NAME = 'DELETE';
  HTTP_PATCH_METHOD_NAME = 'PATCH';

  HTTP_GET_SUCCESS_CODE = 200;
  HTTP_GET_BAD_REQUEST = 400;
  HTTP_GET_NOT_FOUND_CODE = 404;

  HTTP_POST_SUCCESS_CODE = 200;
  HTTP_POST_CREATED_CODE = 201;
  HTTP_POST_NO_CONTENT_CODE = 204;
  HTTP_POST_BAD_REQUEST = 400;
  HTTP_POST_NOT_FOUND_CODE = 404;

  HTTP_PUT_SUCCESS_CODE = 200;
  HTTP_PUT_CREATED_CODE = 201;
  HTTP_PUT_NO_CONTENT_CODE = 204;
  HTTP_PUT_BAD_REQUEST = 400;
  HTTP_PUT_NOT_FOUND_CODE = 404;

  HTTP_DELETE_SUCCESS_CODE = 200;
  HTTP_DELETE_QUEUED_CODE = 202;
  HTTP_DELETE_NO_CONTENT_CODE = 204;
  HTTP_DELETE_BAD_REQUEST = 400;
  HTTP_DELETE_NOT_FOUND_CODE = 404;

  HTTP_PATCH_SUCCESS_CODE = 200;
  HTTP_PATCH_NO_CONTENT_CODE = 204;
  HTTP_PATCH_BAD_REQUEST = 400;
  HTTP_PATCH_NOT_FOUND_CODE = 404;

  HTTP_SERVER_INTERNAL_ERROR = 500;

  constructor() { }
}
